#!/bin/bash

# Directories
export BLASTDB="${XDG_DATA_HOME:-$HOME/.local/share}/blastdb"
export DIAMONDDB="${XDG_DATA_HOME:-$HOME/.local/share}/diamond_db"
THREADS=16

log_step() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
}

download_databases() {
    log_step "Starting database preparation"
    mkdir -p "$BLASTDB" "$DIAMONDDB"
    
    # Create and enter database directory
    DB_DIR="$WORKDIR/blast/databases"
    mkdir -p "$DB_DIR"
    cd "$DB_DIR"

    # Download NCBI nr database
    log_step "Downloading NCBI nr database"
    wget https://ftp.ncbi.nlm.nih.gov/blast/db/FASTA/nr.gz
    pigz -d -p "$THREADS" nr.gz

    # Download taxonomy database from NCBI
    log_step "Downloading taxonomy database"
    wget ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdmp.zip
    unzip taxdmp.zip

    log_step "Downloading accession2taxid mapping"
    wget ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/prot.accession2taxid.FULL.gz
    pigz -d -p "$THREADS" -k prot.accession2taxid.FULL.gz

    # Download new_taxdump for rank information (from your step 3)
    log_step "Downloading new_taxdump for rank information"
    wget https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/new_taxdump/new_taxdump.tar.gz
    tar -xzvf new_taxdump.tar.gz

    # NCBI nt database
    log_step "Downloading NCBI nt database"
    wget https://ftp.ncbi.nlm.nih.gov/blast/db/FASTA/nt.gz
    pigz -d -p "$THREADS" nt.gz

    # Formatting nr database using taxonomy files
    log_step "Creating DIAMOND nr_tax database"
    ./diamond makedb \
        --in nr \
        --taxonnodes nodes.dmp \
        --taxonnames names.dmp \
        --taxonmap prot.accession2taxid.FULL \
        -d nr_tax

    
    mkdir -p /fast2/tmp_diamond

    # Create temp directory for large database processing
    mkdir -p /fast2/tmp_diamond

    # Download and process refseq_protein (from your step 1.1)
    log_step "Processing refseq_protein database"
    mkdir -p refseq_protein
    
    # Download indexed refseq-protein
    rsync -avP rsync://ftp.ncbi.nlm.nih.gov/blast/db/refseq_protein.* refseq_protein/.
    
    # Decompress the database
    cd refseq_protein
    for i in *.tar.gz; do
        pigz -dc -p "$THREADS" "$i" | tar -xvf - && rm -f "$i"
        log_step "Decompressed $i"
    done
    
    # Convert to fasta using blastdbcmd
    blastdbcmd \
        -db refseq_protein \
        -entry all \
        -out ../refseq_protein.fasta
    
    cd ..

    # Create refseq_protein_tax database
    log_step "Creating DIAMOND refseq_protein_tax database"
    diamond makedb \
        --in refseq_protein.fasta \
        -d refseq_protein_tax \
        --taxonnodes nodes.dmp \
        --taxonnames names.dmp \
        --taxonmap prot.accession2taxid.FULL \
        --threads "$THREADS" \
        --tmpdir /fast2/tmp_diamond

    log_step "Diamond database creation completed."
}

download_databases